### ISSUE TITLE
How do I use workload identity with jx boot

### ISSUE THREAD

**Issue by kyounger** [jenkins-x/terraform-google-jx#117]
Ran through this and used the resulting `jx-requirements.yaml` file to `jx boot` on the cluster that was created with very minimal additions/changes (e.g. git details). I can see all the GSA->KSA mappings in the right places, but velero does not seem to take advantage of them, falling back on using a GCP key in a secret to authenticate to the bucket.

Seems like if we're creating these workload identity pieces, we should be able to take advantage of them out of the box. Is there a way to modify the jx-requirements.yaml file to do this?

**Comment by hferentschik** [comment]
> I can see all the GSA->KSA mappings in the right places, but velero does not seem to take advantage of them, falling back on using a GCP key in a secret to authenticate to the bucket.

Why do you think so? When it comes to Velero I am not 100% sure, since Velero is not really fully supported by Jenkins X. It is not really fully understood/documented yet on how it is supposed to be used. There might very well be still something astray. 

When it comes to the other GCP service accounts and the matching Kubernetes service accounts, they are created and matched up in a way that once you are running `jx boot` the charts applied will use the generated service accounts (since the names match up) and hence use workload identity.

You can see here that the cluster is created with workload identity enabled - https://github.com/jenkins-x/terraform-google-jx/blob/master/modules/cluster/main.tf#L32. Not sure whether it even allows falling back to node permissions in this case.

Note, that eventually, we will need to split out the Kubernetes service account creation - see issue #82 

Does that help?

**Comment by hferentschik** [comment]
> Is there a way to modify the jx-requirements.yaml file to do this?

I am not sure what you are after. Can you clarify what you want to do and what you want to change in the requirements file?

**Comment by kyounger** [comment]
Yes, this module does a great job of creating everything properly. The issue is I have no idea how to make jx boot with backups enabled to _use_ the workload identity. It installs velero with a traditional approach, where workload identity isn't used.

Now that I think about it, it's probably more a question/issue for the `jenkins-x/jx` repo proper. The only overlap here is that jx-requirements.yaml is generated by this module, and I sort of figured it would pre-configure it so the workload identity was used. But also to your point, velero isn't really supported.

I was working on a PoC. It's over, and I have to move on (and all resources from that cluster are destroyed). We can close this. I'll refile in `jenkin-x/jx` if/when that needs to happen.
