### ISSUE TITLE
jx-requirements.yml out of sync

### ISSUE THREAD

**Issue by mgoltzsche** [jenkins-x/terraform-google-jx#73]
Initially the tf module generates the `jx-requirements.yml` which is meant to be provided to `jx boot -r`.
However `jx boot` creates a new environment git repository that contains `jx-requirements.yml` as well.
This is potentially inconsistent because changes made using subsequent tf module executions do not make it into the environment repository.

An approach to solve this could be to let the tf module write the information contained within `jx-requirements.yml` into the k8s cluster so that `jx boot` could read it from there more consistently.

**Comment by hferentschik** [comment]
I don't think we can do so much about this atm, except trying to document this better. The templated `jx-requirements.yml` is really just a convenience so that the user does not have to type so much. 

Really the main task of Terraform is to create the cluster. We could just use Terraform outputs to display the bucket URLs and whatever else is needed. Then a user would run just `jx boot` and fill out the needed bits interactively. This would be a clearer separation of concerns and probably less confusion. 
On the other hand, it is more work for the user and there is the risk of getting things wrong when cut&pasting things.

The generated `jx-requirements.yml` is really just a convenience for your initial `jx boot`.

Ideally, you could point Terraform to the `jx-requirement.yml` of the boot config and it does some sort of merge, but that is not possible (and confusing as well).

**Comment by hferentschik** [comment]
Added additional information to README in pull request #77
