### ISSUE TITLE
Generate terraform output for jx-requirements rather than a local file

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/terraform-google-jx#95]
The intention of the `jx-requirements.yaml` file is that it's only ever read at the initial setup of Jenkins X on a new cluster. With that said, producing the local_file resource means that terraform constantly manages that resource and wants to update a file which no longer has as much relevance to the cluster than it did.
The proposal is to define the `jx-requirements.yaml` as an output that could possibly be used to perform the initial boot like (_after the terraform module has created all of the resources_):
```
jx boot -r <(terraform output jx-requirements)
```
Having the Jenkins X requirements available in this manner removes the pain of having to maintain the local file within terraform and the git repository.

**Comment by hferentschik** [comment]
I like the idea. I think it might make things a bit better and relates to issue #75 which poses the question whether the Terraform module should not just define all relevant/interesting outputs, leaving it to the user to populate a `jx-requirements.yml`. Question is where this initial `jx-requirements.yml` would be coming from. Would the user create it from scratch or should the user manually clone the boot repo first and edit the `jx-requirements.yml` in there?

From a technical point of view, the best solution would be if Terraform just defines the outputs, but from a usability perspective, this is not very comfortable.

**Comment by hferentschik** [comment]
Regarding

```
jx boot -r <(terraform output jx-requirements)
```

The rub here is that this command implies that you execute `jx boot` from the directory where the Terraform configuration lives. This will create the dev repo in the same directory. This is potentially problematic since one wants to keep the Terraform scripts in a different repo/directory than the dev repo. In case the Terraform directory is already under version control, `jx boot` might even fail. 

Unfortunately, I think you need to run `terraform output` from inside the terraform setup, which means something theoretically like this is not going to work either:

```
jx boot -r <(terraform -project-dir <terraform-setup-dor> output jx-requirements)
```

**Comment by hferentschik** [comment]
I guess it would need to be something like this: 

```
jx boot -r <$(cd <terraform-dir> && terraform output jx-requirements)
```

@cagiti, any idea what the Windows equivalent would be?

**Comment by hferentschik** [comment]
@vfarcic wdyt?

**Comment by vfarcic** [comment]
I think that it is confusing to be in-between solutions. I would vote either for Terraform and Boot to work together or to be separated. The former is too complicated and would probably produce more problems than benefits. My vote goes for a clear separation between the two. I would suggest to output values (e.g., logs storage address) and use them to create `jx-requirements.yml` independently of Terraform. Otherwise, any solution is flawed because it ignores any future upgrades of either of the two.

**Comment by cagiti** [comment]
> I guess it would need to be something like this:
> 
> ```
> jx boot -r <$(cd <terraform-dir> && terraform output jx-requirements)
> ```
Yeah, I hadn't tested it... It was essentially pseudo code :)

> @cagiti, any idea what the Windows equivalent would be?
Not 100%... maybe it's better to output to a file, then reference that file

**Comment by cagiti** [comment]
> I think that it is confusing to be in-between solutions. I would vote either for Terraform and Boot to work together or to be separated. The former is too complicated and would probably produce more problems than benefits. My vote goes for a clear separation between the two. I would suggest to output values (e.g., logs storage address) and use them to create `jx-requirements.yml` independently of Terraform. Otherwise, any solution is flawed because it ignores any future upgrades of either of the two.

Are you possibly suggesting that `jx boot` should produce the requirements from the terraform outputs?

**Comment by vfarcic** [comment]
No. I'm suggesting that Terraform should produce outputs with individual values and NOT produce `jx-requirements.yml` in any form or way. The outputs from Terraform should be used by people to construct `jx-requirements.yml`. In other words, I don't think that there should be a direct relation between Terraform and JX Boot since we cannot make that relationship work beyond the initial setup.

**Comment by cagiti** [comment]
> No. I'm suggesting that Terraform should produce outputs with individual values and NOT produce `jx-requirements.yml` in any form or way. The outputs from Terraform should be used by people to construct `jx-requirements.yml`. In other words, I don't think that there should be a direct relation between Terraform and JX Boot since we cannot make that relationship work beyond the initial setup.

I see, I think that would be a pretty onerous task for the user... there's would be at least 25 outputs which the user would need to retrieve and use to construct a requirements file.

**Comment by vfarcic** [comment]
I agree @cagiti. However, the alternative is to make it work always, not only initially. It would need to be based on the existing `jx-requirements.yml` and modify it instead of spitting out a new one and ignoring the actual state. Otherwise, what do you do when you `apply` Terraform the second time? Do you replace `jx-requirements.yml` in the `dev` repo with whatever Terraform generates? Do you use it only initially and ignore it with any later changes? What happens if I enable something in Terraform that was disabled before? How do I incorporate that into `jx-requirements.yml`? By doing diff between the two (the one from Terraform and the one in the `dev` repo)?

There are a lot of issues with the current approach and I believe that it should either be decoupled, and that it should be coupled. The current situation is something in between that is very confusing. If it creates `jx-requirements.yml`, I expect it to continue creating it while respecting the actual state of the file, and that's not what it is doing. Since coupling it "for real" is probably the amount of work that no one wants to invest in, decoupling it sounds like a better option.

**Comment by hferentschik** [comment]
> No. I'm suggesting that Terraform should produce outputs with individual values and NOT produce jx-requirements.yml in any form or way. The outputs from Terraform should be used by people to construct jx-requirements.yml. In other words, I don't think that there should be a direct relation between Terraform and JX Boot since we cannot make that relationship work beyond the initial setup.

right, that is basically the idea/question behind #75 

> I see, I understand it's beneficial to decouple them but I think producing an output is a great help  to the end user.

Agreed. I as "power user" like it, but I can see how easy it is to get things wrong. 

Also if we are adding more conditional resource creation (eg for Velero, see #97), it means that a user would have to re-apply the Terraform scripts with the appropriate setting enabled and then manually copy the required/changed settings across to the requirements file in the dev repo. 

> I think that would be a pretty onerous task for the user.

Jupp 

> I agree @cagiti. However, the alternative is to make it work always, not only initially. It would need to be based on the existing jx-requirements.yml and modify it instead of spitting out a new one and ignoring the actual state

I don't think this is possible. Not with Terraform itself. For that, we would need some additional tool and then, for example, call it via a local exec. `jx` itself comes to mind, but now things start for sure to get messy again. Personally, I feel we should not go down this route.

> There are a lot of issues with the current approach and I believe that it should either be decoupled, and that it should be coupled. The current situation is something in between that is very confusing. 

Agreed.

> Since coupling it "for real" is probably the amount of work that no one wants to invest in, decoupling it sounds like a better option.

So what would be the process in this case?

1. `terraform apply && terraform output`
1. `git clone https://github.com/jenkins-x/jenkins-x-boot-config` 
1. edit properties in `jx-requirements.yml` of the clone with the appropriate values from the Terraform output
1. `jx boot`

tedious, but maybe the best solution. Maybe also more of a step towards BYO Kube?

**Comment by hferentschik** [comment]
> Yeah, I hadn't tested it... It was essentially pseudo code :)

>> @cagiti, any idea what the Windows equivalent would be?

> Not 100%... maybe it's better to output to a file, then reference that file

Hmm, which would mean we are back to square one.

**Comment by cagiti** [comment]
> > Yeah, I hadn't tested it... It was essentially pseudo code :)
> 
> > > @cagiti, any idea what the Windows equivalent would be?
> 
> > Not 100%... maybe it's better to output to a file, then reference that file
> 
> Hmm, which would mean we are back to square one.

Not at all, the goal is to not have terraform manage the state of a file that it doesn't need to

**Comment by vfarcic** [comment]
> tedious, but maybe the best solution. Maybe also more of a step towards BYO Kube?

That would be my vote. I see Terraform definitions as helpers, not as the core feature of the project. The moment we couple it with JX (in this case Boot) we are setting certain expectations. If it creates `jx-requirements.yml`, I expect it to maintain it as well. Creating outputs sounds like a reasonable line that marks where one stops and the other starts.

If JX Boot is too complicated to set up, we need to work on making it simpler. Otherwise, we are just moving it from one place to another. At some moment we will change the definitions of the Boot. After that, we might need to start creating additional files. `jx-requirements.yml` might not be there for long.

All that being said, I do not mind that we go down that road, as long as we all understand the potential scope and the expectations that should be met.

**Comment by kyounger** [comment]
I think it's fair to say that tf not generating the entire jx-requirements.xml file is probably a good idea.

It's also pretty trivial to use tf output, but I don't think anyone would mind the tf generated a simple yaml file that could be merged into jx-requirements.yaml. One less thing to think about I suppose.

**Comment by jstrachan** [comment]
`jx-requirements.yml` contains lots of stuff that terraform doesn't comprehend. e.g. whether or not Staging is a remote environment or not. Whether new apps should use public or private git repos by default. What kind of chart repository to use (bucketrepo or chart museum). So we can't just assume the output of terraform is all that data - it basically prevents ever using GitOps for any of these settings.

A work around could be; store the terraform generated `jx-requirements.yml` in Git; if terraform is run again and the generated `jx-requirements.yml` file changes, do a diff and apply it to the one thats in git. (Or basically merge the output of all terraform generated values on top of whats in git).

If terraform defines a bucket name or whatever we should use it - if the user changes a non-terraform owned flag (e.g. changing the kind of chart repository) we shouldn't lose those changes in GitOps.

**Comment by rawlingsj** [comment]
Think this issue can be closed now, BTW for jx3.x we are writing the jx-requirements.yaml from terraform into a configmap in the cluster, the jx git operator will then sync and changes from the terraform plan back to the git repository.  This is the related PR https://github.com/jenkins-x/terraform-google-jx/pull/130.

Even without this latest PR I think this issue can be closed.
