### ISSUE TITLE
Expose ability to specify kubernetes version or release channel for GKE Clusters

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/terraform-google-jx#98]
There doesn't exist to be a method to specify a version of the kubernetes or release channel for GKE clusters in this module. Allowing the user to specify this would be beneficial.

**Comment by vfarcic** [comment]
That is the problem with the module. There is always something missing. Eventually, the values in the module will end up being a collection of all the values used by the resources defined in the module. This is the same issue as the one we had with `jx create cluster`. It just keeps growing and eventually becomes so big that it is easier not to use it.

I believe that it might be a better approach to close the repo with all the definitions so that each person can use it as a base and modify whichever things should be different (that list is ultimately infinite).

P.S. I'm in favor of adding the `version`. I just wanted to stress that the number of things one might need is huge (if not infinite).

**Comment by hferentschik** [comment]
> There doesn't exist to be a method to specify a version of the kubernetes or release channel for GKE clusters in this module. Allowing the user to specify this would be beneficial.

Makes sense and alings with terraform-aws-eks-jx.

**Comment by hferentschik** [comment]
> That is the problem with the module. There is always something missing.

Sure. I intentionally tried to keep the exposed properties to a minimum, expecting to add more. For some, as the here suggested Kubernetes version, it makes sense to expose it. Others I am fully prepared to suggest that making a copy/fork is the better approach.

> This is the same issue as the one we had with jx create cluster

Mind you that it was not the pure number of options which were problematic. The way these options were processed caused issues. From that perspective, we are already in a much better position with Terraform.

**Comment by hferentschik** [comment]
> I'm in favor of adding the version.

So I think we are in agreement in this case :-)

> I just wanted to stress that the number of things one might need is huge (if not infinite).

I think in the end it might not to too bad and for sure not _infinite_ ;-) I think we need to make decisions on a case per case basis.
